version: '3.8'

services:
  # Redis para cache
  redis:
    image: redis:alpine
    container_name: restaurant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    restart: unless-stopped

  # pgAdmin para gerenciar o banco (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: restaurant-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restaurant.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - restaurant_network
    restart: unless-stopped
    profiles:
      - tools

volumes:
  redis_data:
    driver: local

networks:
  restaurant_network:
    driver: bridge